# CH05 Numpy  - 배열의 연산

---
* 날짜:
* 이름:

## 개념정리

데이터 분석에 있어서 배열에 담긴 데이터만큼 중요한 것이 배열의 구조입니다. 특히 머신러닝, 딥러닝에서는 데이터의 선형변환이 주가 되기 때문에 이 과정에서 데이터의 형태 변형이 많이 이루어 집니다. 이번 시간에는 배열의 형태를 변경하고 연결하고, 분할 하는 여러 방법들을 알아보도록 합니다. 

```
import numpy as np
```

---
### **(1) 산술 연산(Arithmetic Operators)**
---

|연산자|범용함수|설명|
|--|--|--|
|+|`np.add`|덧셈|
|-|`np.substract`|뺄셈|
|-|`np.negative`|단항음수|
|*|`np.multiply`|곱셈|
|/|`np.divide`|나눗셈|
|//|`np.floor_divide`|나눗셈 내림|
|**|`np.power`|지수 연산|
|%|`np.mod`|나머지 연산|

파이썬의 수치자료형에서 사용하는 모든 연산을 넘파이 배열에서 사용할 수 있습니다. 

리스트에서는 불가능했던 배열간의 덧셈도 아래와 같이 사용 가능합니다.

```
a = np.array([1,2,3])
b = np.array([-1,2,-3])
a*b
```


#### **|  브로드캐스팅 (Broadcasting)**

NumPy의 배열 연산은 벡터화(vectorized) 연산을 사용합니다. 브로드 캐스팅은 배열 각 요소에 대한 반복적인 계산을 효율적으로 수행합니다.


<p align='center'>
<img src=https://github.com/yebiny/SkillTreePython-DataAnalysis/blob/main/imgs/ch0105-01.png?raw=true width=560>
</p>

---
### **(2) 수학 관련 함수**
---

#### **| 절대값 함수 (Absolute Function)**





* `np.absolute(n)` = `np.abs(n)` : `n`의 절대값 반환

```
print(b)
np.abs(b)
```

#### **| 제곱/제곱근 함수**

* `np.square(n)`: `n`의 제곱을 반환
* `np.sqrt(n)` : `n`의 제곱근을 반환

```
n = 25
print(np.square(n), np.sqrt(n))
```

#### **| 지수/로그 함수**

* `np.exp(n)` : 자연상수 `e`(=~2.71..)의 `n` 제곱을 반환
* `np.exp2(n)` : 상수 `2`의 `n` 제곱을 반환


```
[np.exp2(n) for n in range(10)]
```


* `np.log(n)` : 밑이 `e`인 로그값을 반환합니다. 
* `np.log2(n)` : 밑이 `2`인 로그값을 반환합니다.
* `np.log10(n)` : 밑이 `10`인 로그값을 반환합니다.

```
n = [10,100,1000,10000]
np.log10(n)
```

#### **| 삼각 함수(Trigonometrical Function)**

|함수|설명|
|--|--|
|`np.sin`|사인|
|`np.cos`|코사인|
|`np.tan`|탄젠트|
|`np.arcsin`|아크 사인|
|`np.argcos`|아크 코사인|
|`np.argtan`|아크 탄젠트|
|`np.sinh`|하이퍼볼릭 사인|
|`np.cosh`|하이퍼볼릭 코사인|
|`np.tanh`|하이퍼볼릭 탄젠트|
|`np.arcsinh`|하이퍼볼릭 아크 사인|
|`np.arccosh`|하이퍼볼릭 아크 코사인|
|`np.arctanh`|하이퍼볼릭 아크 탄젠트|
|`np.deg2rad`|각도를 라디안으로 변환|
|`np.rad2deg`|라디안을 각도로 변환|
|`np.hypot`|유클리드 거리계산|

학창시절 아래 삼각함수 표를 외워본 경험이 있을 겁니다. 더이상 이를 외울 필요는 없습니다. 코드가 알아서 해줄테니까요. 값이 똑같이 나오는지 확인해 봅시다.

<p align='center'>
<img src=https://github.com/yebiny/SkillTreePython-DataAnalysis/blob/main/imgs/ch0105-02.png?raw=true width=500>
</p>

```
n = 0
np.sin(n), np.cos(n), np.tan(n)
```

#### **| 집계 함수(Aggregate Functions)**

|함수|설명|
|--|--|
|`np.sum()`|배열 내 합을 반환|
|`np.cumsum()`|배열 내 누적합 반환|
|`np.prod()`|배열 내 곱 반환|
|`np.diff()`|배열 내 차 반환|
|`np.min()`|최소값 반환|
|`np.max()`|최대값 반환|
|`np.mean()`|평균 반환|
|`np.std()`|표준편차 반환|
|`np.var()`|분산 반환|
|`np.median()`|중앙값 반환|
|`np.argmin()`|최소값 인덱스 반환|
|`np.argmax()`|최소값 인덱스 반환|


```
print(a)
print('누적합: ',np.cumsum(a))
print('곱: ',np.prod(a))
print('차: ',np.diff(a))
print('중앙값: ',np.median(a))
```

머신러닝에서 자주 사용되는 함수는 `np.argmax`입니다. `np.argmax`는 최대값의 인덱스를 반환하는데요, 최대값 자체가 아닌 인덱스가 언제 필요할까요?

예시를 들어 봅시다. `y`에 카드 이름이, `x`에는 각 카드가 뽑힐 확률이 들어 있습니다. 뽑힐 확률이 가장 높은 카드를 아래와 같이 구할 수 있습니다.

```
x = [0.1, 0.2, 0.6, 0.1]
y = ['a', 'b', 'c', 'd']
idx = np.argmax(x)
print(y[idx]) # 팬시 인덱싱
```

---
### **(3) 벡터/행렬 연산**
---

|함수|설명|
|--|--|
|`np.matmul()`|=`@`, 행렬곱|
|`np.dot()`|내적|
|`np.prod()`|외적|


* `np.matmul(a1, a2)` : 배열 `a1`과 `a2`의 행렬곱을 수행합니다. 

일반적인 행렬곱을 `matmul`을 통해서 할 수 있습니다. 

```
A = np.array([[1,2],
              [0,1]])
B = np.array([[1,0],
              [0,1]])
print(np.matmul(A,B))
print(A@B)
```

* `np.dot(a1, a2)`: 배열 `a1`과 `a2`의 벡터 내적을 수행합니다.

벡터 내적은 벡터 내 같은 인덱스의 값을 곱하고 모두 더한 것입니다.

```
print(a, b)
print(sum(a*b))
print(np.dot(a,b))
```

---
### **(4) 비교 연산**
---

비교 연산자를 이용하면 `boolean` 값으로 이루어진 배열을 반환합니다.


#### **| 값 비교**


|연산자|비교 범용 함수|
|--|--|
|`==`|`np.equal`|
|`!=`|`np.not_equal`|
|`<`| `np.less`|
|`<=`|`np.less_equal`|
|`>`| `np.greater`|
|`>=`|`np.greater_equal`|

```
print(a)
print(b)
a==b, a<b, a>b
```


#### **| 예외값 비교**



|함수|설명|
|--|--|
|`np.isinf`|`inf` 값이면 `True`, 아니면 `False`|
|`np.isfinite`|`inf, nan` 값이면 `False`, 아니면 `True`|
|`np.isnan`|`nan` 값이면 `True`, 아니면 `False`|

```
a = [np.inf, np.nan, 0]
print(np.isinf(a))
print(np.isfinite(a))
print(np.isnan(a))
```

#### **| 논리 연산자**

|함수|설명|
|--|--|
|`np.all()`|모두 `True`일때 `True` 반환|
|`np.any()`|모두 `False`일때 `False` 반환|

파이썬의 논리 연산자와 동일 합니다. 아래와 같이 숫자 자료형을 바로 넣으면 0 일 때는 `False`, 그 외에는 `True`로 인식하여 연산이 진행됩니다.

```
a = [1,0,1,1,0]
np.all(a), np.any(a)
```

---
### **(5) 정렬**
---


|함수|설명|
|--|--|
|`np.sort()`|오름차순 정렬|
|`np.argsort()`|index 정렬|
|`np.partition()`|`k`개의 작은값 반환|

* `np.sort(a, axis=axis)` : 배열 `a`를 오름차순으로 정렬합니다. 

```
np.random.seed(42);a = np.random.randint(0,12,(3,4))
print(a)
print('axis=0: 위에서 아래로 정렬')
print(np.sort(a, axis=0))
print('axis=1: 좌에서 우로 정렬')
print(np.sort(a, axis=1))
```

* `np.argsort(a, axis=axis)` : 배열 `a`를 오름차순 정렬하는  인덱스를 반환

위에서 배웠던 `np.argmax`와 마찬가지로 팬시 인덱싱에서 유용하게 사용됩니다. 

아래와 같이 월별(x) 판매수(y)가 주어졌을 때 판매수 순으로 정렬하고자 합니다. 

```
x = np.array(['1월', '2월', '3월'])
y = np.array([500,230,350])
sort_idx = np.argsort(y)
print(sort_idx)
x[sort_idx][::-1] # 팬시 인덱싱
```

## 문제풀이
---

**예제 01**

아래 그림에 있는 산술연산을 각각 코드로 구현하세요

<p align='center'>
<img src=https://github.com/yebiny/SkillTreePython-DataAnalysis/blob/main/imgs/ch0105-03.png?raw=true width=400>
</p>

**예제 02**


아래는 `sum`의 용례를 그림으로 표현한 것입니다. 각 경우에 대해 코드로 구현하세요.

<p align='center'>
<img src=https://github.com/yebiny/SkillTreePython-DataAnalysis/blob/main/imgs/ch0105-04.png?raw=true width=460>
</p>

**예제 03**

위와 똑같은 방법으로 3가지 경우에 대해 `min()`을 수행하세요

**예제 04**

위와 똑같은 방법으로 3가지 경우에 대해 `argmax()`을 수행하세요

**예제 05**

위와 똑같은 방법으로 3가지 경우에 대해 `std()`을 수행하세요

**예제 06**

아래는 `any`의 용례를 그림으로 표현한 것입니다. 각 경우에 대해 코드로 구현하고, 왜 이런 결과가 나오는지 정리하세요.


<p align='center'>
<img src=https://github.com/yebiny/SkillTreePython-DataAnalysis/blob/main/imgs/ch0105-05.png?raw=true width=580>
</p>

**예제 07**

위와 똑같은 방법으로 3가지 경우에 대해 `all()`을 수행하고, 왜 이런 결과가 나오는지 정리하세요.

**예제 08**


1에서 100까지의 랜덤값을 가지고 형태가 `(40)` 인 1차원 배열을 `a08`로 바인딩하세요

**예제 09**

`a08`에서 50보다 큰 수만 가지는 배열을 불리언 연산자를 이용해서 생성하세요.

**예제 10**

`a08`에서 50 이하이며 3의 배수만 가지는 배열을 불리언 연산자를 이용해 생성하세요

**예제 11**

`a08`에서 90이상이거나 10이하인 수만 가지는 배열을 불리언 연산자를 이용해 생성하세요

**예제 12**


`a08`을 shape가 `(8,5)`인 2차원 배열로 변환하고 `a12`로 바인딩 하세요.

**예제 13**


`a12`를 복사하여 `a13`으로 바인딩하고 이를 각 행 별로 정렬하세요

**예제 14**


`a12`를 복사하여 `a14`로 바인딩하고 각 열 별로 가장 작은수 3개를 찾으세요

$A$, $B$, $C$를 아래와 같이 정의하세요.

\begin{align*}
 A&= 
\begin{pmatrix}
1 &2  &1 \\ 
2 &1 & 1\\ 
-1 & 0 & 1
\end{pmatrix}
\end{align*}

\begin{align*}
 B&= 
\begin{pmatrix}
1 &0 \\ 
0 &1 \\ 
1 & 0 
\end{pmatrix}
\end{align*}

\begin{align*}
 C&= 
\begin{pmatrix}
1 \\ 
0  \\ 
-1  
\end{pmatrix}
\end{align*}

**예제 15**


$A$, $B$ 의 행렬곱

**예제 16**


$A$, $C$ 의 행렬곱

**예제 17**


$A * C$

**예제 18**


$B$와 $B^T$의 내적


20명의 학생의 번호와, 키와, 수행평가 점수가 아래와 같이 정의 되어 있습니다. 

```
idx = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
tall = [178, 171, 179, 173, 152, 157, 175, 180, 182, 165, 160, 164, 174, 163, 158, 159, 172, 155, 177, 162]
score = [57, 64, 85, 30, 58, 72, 84, 63, 49, 94, 70, 54, 60, 68, 74, 78, 92, 86, 51, 37]
```

**예제 19**

키가 큰 순으로 학생들의 번호(idx)를 정렬하세요.

**예제 20**

수행평가 점수가 낮은 순으로 학생들의 번호(idx)를 정렬하세요.